# Generated by Django 4.2 on 2026-04-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VP', '0010_panel_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
