# Generated by Django 4.2 on 2026-04-04 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VP', '0011_member_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='mobile_number',
        ),
    ]
