# Generated by Django 4.2 on 2026-04-08 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VP', '0016_event_end_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventresult',
            unique_together=set(),
        ),
    ]
